title: Geluk en Mentale gezondheid
author: InfoVis Group B2
logo: # Als we een logo willen toevoegen.
html:
  favicon:  # Hier kunnen we een favicon toevoegen.
  use_repository_button: true

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/MotasemWahbi/information-visualization
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
